apiVersion: v1
kind: Service
metadata:
  name: svc-tasty-service
spec:
  type: LoadBalancer
  selector:
    app: sistema-tasty-svc-main
  ports:
    #  Consegui acesso ao EKS somente se deixar os dois valores de portas iguais, preciso validar o motivo.
    - port: 8000
      targetPort: 8000 
    

